sudo: required

language: c

os:
 - linux

compiler:
 - gcc

before_script:
 - git clone https://github.com/jedisct1/libsodium.git --branch=stable
 - cd libsodium
 - env CPPFLAGS=-DED25519_NONDETERMINISTIC ./configure --disable-dependency-tracking
 - sudo make install
 - sudo ldconfig
 - cd ..
 - mkdir build
 - cd build
 - cmake ..

script:
 - make -j$(nproc)

matrix:
 - fast_finish: true
